import type { IpcChannel } from '@shared/types/ipc';

export const CHANNELS = {
  appPing: 'app:ping',
  importPickFile: 'import:pickFile',
  importExtract: 'import:extract',
  importResolveAccount: 'import:resolveAccount',
  importConfirm: 'import:confirm',
  categorizePending: 'categorize:pending',
  categorizeBatch: 'categorize:batch',
  dashboardGetAccounts: 'dashboard:getAccounts',
  dashboardGetTransactions: 'dashboard:getTransactions',
  dashboardAggregate: 'dashboard:aggregate',
  dashboardMetrics: 'dashboard:metrics',
  dashboardCashflow: 'dashboard:cashflow',
  dashboardNetWorth: 'dashboard:netWorth',
  recurringList: 'recurring:list',
  accountsCreate: 'accounts:create',
  accountsUpdate: 'accounts:update',
  accountsDelete: 'accounts:delete',
  accountsSetDeclaredBalance: 'accounts:setDeclaredBalance',
  categoriesList: 'categories:list',
  categoriesRename: 'categories:rename',
  categoriesCreate: 'categories:create',
  categoriesDelete: 'categories:delete',
  transactionsSetCategory: 'transactions:setCategory',
  transactionsUpdate: 'transactions:update',
  transactionsDelete: 'transactions:delete',
  transactionsRestore: 'transactions:restore',
  transactionsSetTransfer: 'transactions:setTransfer',
  banksLearn: 'banks:learn',
  modelStatus: 'model:status',
  modelDownloadStart: 'model:download:start',
  modelDownloadCancel: 'model:download:cancel',
  modelRemove: 'model:remove',
  modelDetectSelection: 'model:selection:detect',
  settingsGetCategorizeOptOut: 'settings:getCategorizeOptOut',
  settingsSetCategorizeOptOut: 'settings:setCategorizeOptOut',
} as const satisfies Record<string, IpcChannel>;
