import type { IpcChannel } from '@shared/types/ipc';

export const CHANNELS = {
  appPing: 'app:ping',
  importPickFile: 'import:pickFile',
  importExtract: 'import:extract',
  importResolveAccount: 'import:resolveAccount',
  importConfirm: 'import:confirm',
  dashboardGetAccounts: 'dashboard:getAccounts',
  dashboardGetTransactions: 'dashboard:getTransactions',
  dashboardAggregate: 'dashboard:aggregate',
  dashboardMetrics: 'dashboard:metrics',
  accountsCreate: 'accounts:create',
  accountsUpdate: 'accounts:update',
  accountsDelete: 'accounts:delete',
  categoriesList: 'categories:list',
  categoriesRename: 'categories:rename',
  categoriesCreate: 'categories:create',
  categoriesDelete: 'categories:delete',
  transactionsSetCategory: 'transactions:setCategory',
  transactionsUpdate: 'transactions:update',
  transactionsDelete: 'transactions:delete',
  transactionsRestore: 'transactions:restore',
  banksLearn: 'banks:learn',
} as const satisfies Record<string, IpcChannel>;
